name: sentry_dart_frog
description: Sentry integration for dart_frog. Capture errors and trace performance
version: 0.2.2
repository: https://github.com/ueman/dart-packages/
issue_tracker: https://github.com/ueman/dart-packages/issues

topics:
  - server
  - http
  - middleware
  - error
  - dart-frog

funding:
  - https://github.com/sponsors/ueman

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_frog: ^1.0.0
  sentry: ^8.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.16.0
